server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /api/feature/ {
        proxy_pass http://integration-test-feature-backend:5101/api/v1/tools/;
        proxy_set_header X-Request-ID $request_id;
        proxy_pass_request_headers on;
    }

    location /api/ai/ {
        proxy_pass http://ai-mode:5005/api/v1/;
        proxy_set_header X-Request-ID $request_id;
        proxy_pass_request_headers on;
    }
}
