"""Assemble a base/head comparison from two capture directories into a standalone gallery.

The inputs may come from an untrusted pull request, so only bounded JSON fields and validated PNGs
are read, every string is length-limited, and HTML is generated by trusted templates.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping, Sequence
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from scripts.visual import pixels as px
from scripts.visual.cases import CASES
from scripts.visual.gallery import render_gallery
from scripts.visual.pngsafe import decode_png, encode_png
from scripts.visual.policy import (
    CASE_ID,
    FIXED_TIME,
    MAX_JSON_BYTES,
    MAX_VIEWS,
    PROVIDERS,
    SHA,
    VIEWPORT_HEIGHT,
    VIEWPORT_WIDTH,
    section_for,
)

STATUSES = ("changed", "incomplete", "base unavailable", "subtle", "unchanged")


@dataclass
class Side:
    """One revision's capture records, keyed by case ID."""

    records: dict[str, dict[str, Any]] = field(default_factory=dict)
    sha: str | None = None
    providers: set[str] = field(default_factory=set)


@dataclass
class Report:
    """A built comparison: display rows, counts, provenance and every image it references."""

    rows: list[dict[str, Any]]
    summary: dict[str, int]
    metadata: dict[str, Any]
    files: list[str]


def _text(value: object, limit: int) -> str:
    return value[:limit] if isinstance(value, str) else ""


def _texts(value: object, count: int, limit: int) -> list[str]:
    if not isinstance(value, list):
        return []
    return [str(item)[:limit] for item in value[:count]]


def read_side(directory: Path, side: str, *, strict: bool = True) -> Side:
    """Read every ``capture-<provider>.json`` in a directory as bounded records.

    ``strict`` requires each manifest to label itself with this side, as CI captures do.
    """
    result = Side()
    shas: set[str] = set()
    for provider in PROVIDERS:
        path = directory / f"capture-{provider}.json"
        if not path.is_file():
            continue
        raw = path.read_bytes()
        if len(raw) > MAX_JSON_BYTES:
            raise ValueError(f"{path.name} exceeds the metadata size limit")
        data = json.loads(raw)
        if not isinstance(data, dict) or data.get("schema") != 1:
            raise ValueError(f"{path.name} has an unsupported schema")
        if strict and data.get("revision") not in (None, side):
            raise ValueError(f"{path.name} belongs to a different revision")
        if data.get("provider") not in (None, provider):
            raise ValueError(f"{path.name} belongs to a different provider")
        if isinstance(data.get("revisionSha"), str):
            if not SHA.fullmatch(data["revisionSha"]):
                raise ValueError(f"{path.name} has an invalid revision SHA")
            shas.add(data["revisionSha"])
        cases = data.get("cases")
        if not isinstance(cases, list) or len(cases) > MAX_VIEWS:
            raise ValueError(f"{path.name} has an invalid case list")
        result.providers.add(provider)
        for row in cases:
            if not isinstance(row, dict) or not CASE_ID.fullmatch(str(row.get("id", ""))):
                continue
            case_id = str(row["id"])
            if case_id in result.records:
                raise ValueError(f"{case_id} was captured twice")
            if len(result.records) >= MAX_VIEWS:
                raise ValueError("the capture inventory exceeds its limit")
            result.records[case_id] = {
                "section": section_for(case_id, row.get("section")),
                "provider": provider,
                "path": _text(row.get("path"), 300),
                "state": _text(row.get("state"), 300),
                "scenario": _text(row.get("scenario"), 40),
                "status": row.get("status")
                if row.get("status") in ("captured", "failed")
                else "incomplete",
                "errors": _texts(row.get("errors"), 5, 500),
                "notes": _texts(row.get("notes"), 5, 400),
            }
    if len(shas) > 1:
        raise ValueError(f"{side} captures come from different revisions")
    result.sha = next(iter(shas), None)
    return result


def store_image(directory: Path, data: bytes, files: set[str]) -> str:
    """Write bytes once under their SHA-256 name; identical pixels share one URL everywhere."""
    name = f"{hashlib.sha256(data).hexdigest()}.png"
    target = directory / name
    if not target.exists():
        target.write_bytes(data)
    files.add(name)
    return name


def _compare(
    row: dict[str, Any], decoded: Mapping[str, px.Pixels], images: Path, files: set[str]
) -> None:
    base, head = px.align(decoded["base"], decoded["head"])
    delta = px.channel_delta(base, head)
    analyses: dict[int, px.Analysis] = {}
    masks: dict[int, px.Mask] = {}
    for threshold in px.THRESHOLDS:
        if threshold and analyses[0]["changed"] == 0:
            analyses[threshold], masks[threshold] = analyses[0], masks[0]
            continue
        analyses[threshold], masks[threshold] = px.analyse(delta, threshold)
    size_changed = decoded["base"].shape[0] != decoded["head"].shape[0]
    row["change"] = px.classify(analyses, size_changed=size_changed)
    row["analyses"] = {}
    for threshold, analysis in analyses.items():
        heat = (
            store_image(images, encode_png(px.heatmap(masks[threshold])), files)
            if analysis["changed"]
            else None
        )
        row["analyses"][str(threshold)] = {**analysis, "heat": heat}
    if row["change"] != "changed":
        return
    areas = px.merge_areas(analyses[0]["regions"])
    canvas_height = base.shape[0]
    difference = px.difference_image(head, masks[0], areas[:12])
    window = px.preview_window(areas, canvas_height)
    focus = []
    for area in areas[:2]:
        rect = px.focus_rect(area, canvas_height)
        if rect is None:
            continue
        focus.append(
            {
                "area": area,
                "rect": rect,
                "base": store_image(images, encode_png(px.crop(base, rect)), files),
                "head": store_image(images, encode_png(px.crop(head, rect)), files),
            }
        )
    significant = analyses[8]["regions"]
    row["review"] = {
        "areas": areas[:12],
        "areaCount": len(areas),
        "difference": store_image(images, encode_png(difference), files),
        "preview": store_image(images, encode_png(px.crop(difference, window)), files),
        "previewRect": window,
        "focus": focus,
        "key": px.area_key(px.merge_areas(significant) if significant else areas),
    }


def group_shared_changes(rows: list[dict[str, Any]]) -> None:
    """Fold views whose changed areas coincide into the first such view in their section."""
    leaders: dict[str, dict[str, Any]] = {}
    for row in rows:
        review = row.get("review")
        if not review:
            continue
        key = f"{row['section']}:{review['key']}"
        leader = leaders.setdefault(key, row)
        if leader is not row:
            leader["review"].setdefault("sharedWith", []).append(row["id"])
            review["sameAs"] = leader["id"]


def summarise(rows: list[dict[str, Any]]) -> dict[str, int]:
    """Count rows by comparison status."""
    counts = {status: sum(row["change"] == status for row in rows) for status in STATUSES}
    return {
        "changed": counts["changed"],
        "subtle": counts["subtle"],
        "unchanged": counts["unchanged"],
        "incomplete": counts["incomplete"],
        "baseUnavailable": counts["base unavailable"],
        "total": len(rows),
    }


def build_report(
    *,
    base_dir: Path,
    head_dir: Path,
    output: Path,
    title: str = "Visual comparison",
    metadata: Mapping[str, Any] | None = None,
    strict: bool = True,
    expected_providers: Sequence[str] = (),
) -> Report:
    """Compare two capture directories and write ``index.html``, ``changes.json`` and images."""
    images = output / "img"
    images.mkdir(parents=True, exist_ok=True)
    files: set[str] = set()
    base = read_side(base_dir, "base", strict=strict)
    head = read_side(head_dir, "head", strict=strict)
    if any(provider not in PROVIDERS for provider in expected_providers):
        raise ValueError("unknown expected capture provider")
    details = dict(metadata or {})
    if strict and base.sha and base.sha == head.sha:
        raise ValueError("cannot compare a revision against itself")
    expected = details.get("expectedHeadSha")
    if head.sha and expected and head.sha != expected:
        raise ValueError("the captured head does not match the workflow run")
    details.update(baseSha=base.sha, headSha=head.sha)
    # Trusted manifest order first; views a change introduces follow, with bounded labels.
    inventory: dict[str, dict[str, Any]] = {
        case.id: {
            "section": case.section,
            "provider": case.provider,
            "path": case.path,
            "state": case.state,
            "scenario": case.scenario,
        }
        for case in CASES
    }
    for case_id, record in [*base.records.items(), *head.records.items()]:
        if case_id not in inventory:
            if len(inventory) >= MAX_VIEWS:
                raise ValueError("the combined inventory exceeds its limit")
            inventory[case_id] = {
                key: record[key] for key in ("section", "provider", "path", "state", "scenario")
            }
    rows: list[dict[str, Any]] = []
    for case_id, item in inventory.items():
        base_record, head_record = base.records.get(case_id), head.records.get(case_id)
        expected_case = item["provider"] in expected_providers
        if base_record is None and head_record is None and not expected_case:
            continue  # neither side captured this provider (for example a local fixture-only run)
        if expected_case:
            for captures in (base, head):
                if case_id in captures.records:
                    continue
                missing = (
                    f"{item['provider']} capture artifact missing; inspect the capture workflow log"
                    if item["provider"] not in captures.providers
                    else "view missing from the capture manifest"
                )
                captures.records[case_id] = {
                    **item,
                    "status": "incomplete",
                    "errors": [missing],
                    "notes": [],
                }
            base_record = base.records[case_id]
            head_record = head.records[case_id]
        current: dict[str, Any] = head_record or base_record or {}
        row: dict[str, Any] = {
            "id": case_id,
            **item,
            "path": current.get("path") or item["path"],
            "state": current.get("state") or item["state"],
            "base": base_record,
            "head": head_record,
        }
        decoded: dict[str, px.Pixels] = {}
        for side, directory, capture in (
            ("base", base_dir, base_record),
            ("head", head_dir, head_record),
        ):
            if capture is None or capture["status"] != "captured":
                continue
            path = directory / f"{case_id}.png"
            if not path.is_file():
                capture["status"] = "incomplete"
                capture["errors"].append("screenshot missing from the capture artifact")
                continue
            data = path.read_bytes()
            try:
                decoded[side] = decode_png(data)
            except ValueError as exc:
                capture["status"] = "incomplete"
                capture["errors"].append(f"screenshot rejected: {exc}")
                continue
            row[f"{side}Image"] = store_image(images, data, files)
            row[f"{side}Height"] = int(decoded[side].shape[0])
        if "head" not in decoded:
            row["change"] = "incomplete"
        elif "base" not in decoded:
            row["change"] = "base unavailable"
        else:
            _compare(row, decoded, images, files)
        rows.append(row)
    group_shared_changes(rows)
    summary = summarise(rows)
    write_report_pages(output=output, title=title, rows=rows, summary=summary, metadata=details)
    return Report(rows=rows, summary=summary, metadata=details, files=sorted(files))


def change_summary(
    rows: list[dict[str, Any]],
    summary: Mapping[str, int],
    metadata: Mapping[str, Any],
    image_root: str,
) -> dict[str, Any]:
    """Machine-readable review data for scripts and agents: exact metrics, areas and image URLs."""

    def url(name: object) -> str | None:
        return f"{image_root}{name}" if isinstance(name, str) else None

    return {
        "schema": 1,
        "baseSha": metadata.get("baseSha"),
        "headSha": metadata.get("headSha"),
        "viewport": {"width": VIEWPORT_WIDTH, "height": VIEWPORT_HEIGHT, "fixedTime": FIXED_TIME},
        "summary": dict(summary),
        "views": [
            {
                "id": row["id"],
                "section": row["section"],
                "provider": row["provider"],
                "path": row["path"],
                "state": row["state"],
                "change": row["change"],
                "changedPixels": (row.get("analyses") or {}).get("0", {}).get("changed"),
                "percent": (row.get("analyses") or {}).get("0", {}).get("percent"),
                "heights": {"before": row.get("baseHeight"), "after": row.get("headHeight")},
                "areas": (row.get("review") or {}).get("areas", []),
                "sameAreasAs": (row.get("review") or {}).get("sameAs"),
                "images": {
                    "before": url(row.get("baseImage")),
                    "after": url(row.get("headImage")),
                    "difference": url((row.get("review") or {}).get("difference")),
                },
                "limitations": [
                    f"{side}: {message}"
                    for side in ("base", "head")
                    for message in ((row.get(side) or {}).get("errors") or [])
                ],
            }
            for row in rows
        ],
    }


def write_report_pages(
    *,
    output: Path,
    title: str,
    rows: list[dict[str, Any]],
    summary: Mapping[str, int],
    metadata: Mapping[str, Any],
    image_root: str = "img/",
    history_url: str | None = None,
) -> None:
    """Write the gallery page and its JSON companions."""
    output.mkdir(parents=True, exist_ok=True)
    (output / "index.html").write_text(
        render_gallery(
            title=title,
            rows=rows,
            summary=summary,
            metadata=metadata,
            image_root=image_root,
            history_url=history_url,
        ),
        encoding="utf-8",
    )
    (output / "summary.json").write_text(json.dumps(dict(summary), indent=2) + "\n")
    (output / "changes.json").write_text(
        json.dumps(change_summary(rows, summary, metadata, image_root), indent=2) + "\n"
    )
