-- Register validated current publisher services. Migration 056 was already applied by development reload.

INSERT INTO ops.source_definition (id,name,publisher,source_url,adapter_key,cadence,licence_id,licence_url,redistribution_policy,target_features_json,status,notes,created_at,updated_at,version) VALUES ('b4e1417b-bdd3-5df5-a243-1494c2f76479','NSW cadastral lots','NSW Spatial Services','https://portal.spatial.nsw.gov.au/server/rest/services/NSW_Land_Parcel_Property_Theme_multiCRS/FeatureServer/8','nsw-cadastre-source','source-release-driven','nsw-spatial-open-data','https://www.spatial.nsw.gov.au/copyright','licence-controlled','["feature-1"]'::jsonb,'active','Producer-owned reference source; downstream integration is separate.',now(),now(),1) ON CONFLICT (id) DO NOTHING;
INSERT INTO ops.job_definition (id,source_definition_id,name,profile_key,profile_version,adapter_key,adapter_version,release_builder_key,release_builder_version,import_profile_key,import_profile_version,target_feature,dataset_id,refresh_strategy,default_run_mode,quality_policy_key,quality_policy_version,status,schedule_text,created_at,updated_at,version) VALUES ('7d8399ea-29e7-56fe-87fb-e5bb7c890752','b4e1417b-bdd3-5df5-a243-1494c2f76479','NSW cadastral lots','nsw-cadastre','1.0.0','nsw-cadastre-source','1.0.0','reference-feature','1.0.0','nsw-cadastre','1.0.0','feature-1','nsw-cadastre','full_snapshot','full_refresh','nsw-cadastre','1.0.0','active',NULL,now(),now(),1) ON CONFLICT (id) DO NOTHING;

INSERT INTO ops.source_definition (id,name,publisher,source_url,adapter_key,cadence,licence_id,licence_url,redistribution_policy,target_features_json,status,notes,created_at,updated_at,version) VALUES ('3ba8c326-5293-5e1e-bee9-e4b1fc56c2e7','NSW EPI planning controls','NSW Department of Planning, Housing and Infrastructure','https://mapprod1.environment.nsw.gov.au/arcgis/rest/services/Planning/EPI_Primary_Planning_Layers/MapServer','nsw-planning-controls-source','source-release-driven','cc-by','https://www.planningportal.nsw.gov.au/opendata/dataset/','attributed-derived-release','["feature-1"]'::jsonb,'active','Producer-owned reference source; downstream integration is separate.',now(),now(),1) ON CONFLICT (id) DO NOTHING;
INSERT INTO ops.job_definition (id,source_definition_id,name,profile_key,profile_version,adapter_key,adapter_version,release_builder_key,release_builder_version,import_profile_key,import_profile_version,target_feature,dataset_id,refresh_strategy,default_run_mode,quality_policy_key,quality_policy_version,status,schedule_text,created_at,updated_at,version) VALUES ('fa4506fb-3ac3-5f1b-9fac-6cff528e7db5','3ba8c326-5293-5e1e-bee9-e4b1fc56c2e7','NSW EPI planning controls','nsw-planning-controls','1.0.0','nsw-planning-controls-source','1.0.0','reference-feature','1.0.0','nsw-planning-controls','1.0.0','feature-1','nsw-planning-controls','full_snapshot','full_refresh','nsw-planning-controls','1.0.0','active',NULL,now(),now(),1) ON CONFLICT (id) DO NOTHING;

INSERT INTO ops.source_definition (id,name,publisher,source_url,adapter_key,cadence,licence_id,licence_url,redistribution_policy,target_features_json,status,notes,created_at,updated_at,version) VALUES ('d8192ca9-7087-5808-b4e5-88525b3f89b4','NSW bushfire prone land','NSW Rural Fire Service','https://mapprod3.environment.nsw.gov.au/arcgis/rest/services/Fire/BFPL/MapServer/0','nsw-bushfire-prone-land-source','source-release-driven','cc-by-4-0','https://creativecommons.org/licenses/by/4.0/','attributed-derived-release','["feature-1"]'::jsonb,'active','Producer-owned reference source; downstream integration is separate.',now(),now(),1) ON CONFLICT (id) DO NOTHING;
INSERT INTO ops.job_definition (id,source_definition_id,name,profile_key,profile_version,adapter_key,adapter_version,release_builder_key,release_builder_version,import_profile_key,import_profile_version,target_feature,dataset_id,refresh_strategy,default_run_mode,quality_policy_key,quality_policy_version,status,schedule_text,created_at,updated_at,version) VALUES ('62d5a853-1af2-50f8-a467-12f00ba3d222','d8192ca9-7087-5808-b4e5-88525b3f89b4','NSW bushfire prone land','nsw-bushfire-prone-land','1.0.0','nsw-bushfire-prone-land-source','1.0.0','reference-feature','1.0.0','nsw-bushfire-prone-land','1.0.0','feature-1','nsw-bushfire-prone-land','full_snapshot','full_refresh','nsw-bushfire-prone-land','1.0.0','active',NULL,now(),now(),1) ON CONFLICT (id) DO NOTHING;

INSERT INTO ops.source_definition (id,name,publisher,source_url,adapter_key,cadence,licence_id,licence_url,redistribution_policy,target_features_json,status,notes,created_at,updated_at,version) VALUES ('d17257af-cd9a-5e1c-8c4a-1e0840cc11ff','NSW published flood planning controls','NSW Department of Planning, Housing and Infrastructure','https://mapprod1.environment.nsw.gov.au/arcgis/rest/services/Planning/EPI_Protection_Layers/MapServer/1','nsw-flood-planning-source','source-release-driven','cc-by','https://www.planningportal.nsw.gov.au/opendata/dataset/','attributed-derived-release','["feature-1"]'::jsonb,'active','Producer-owned reference source; downstream integration is separate.',now(),now(),1) ON CONFLICT (id) DO NOTHING;
INSERT INTO ops.job_definition (id,source_definition_id,name,profile_key,profile_version,adapter_key,adapter_version,release_builder_key,release_builder_version,import_profile_key,import_profile_version,target_feature,dataset_id,refresh_strategy,default_run_mode,quality_policy_key,quality_policy_version,status,schedule_text,created_at,updated_at,version) VALUES ('77a8bb12-08c5-533c-a0db-40058a249c92','d17257af-cd9a-5e1c-8c4a-1e0840cc11ff','NSW published flood planning controls','nsw-flood-planning','1.0.0','nsw-flood-planning-source','1.0.0','reference-feature','1.0.0','nsw-flood-planning','1.0.0','feature-1','nsw-flood-planning','full_snapshot','full_refresh','nsw-flood-planning','1.0.0','active',NULL,now(),now(),1) ON CONFLICT (id) DO NOTHING;

INSERT INTO ops.source_definition (id,name,publisher,source_url,adapter_key,cadence,licence_id,licence_url,redistribution_policy,target_features_json,status,notes,created_at,updated_at,version) VALUES ('dcc3a69b-47b3-599a-bda1-78d4a9538ead','ABS 2021 NSW statistical locality and LGA boundaries','Australian Bureau of Statistics','https://geo.abs.gov.au/arcgis/rest/services/ASGS2021/SAL/MapServer/0','abs-geography-2021-source','census-release-driven','cc-by-4-0','https://www.abs.gov.au/website-privacy-copyright-and-disclaimer','attributed-derived-release','["feature-1"]'::jsonb,'active','Producer-owned reference source; downstream integration is separate.',now(),now(),1) ON CONFLICT (id) DO NOTHING;
INSERT INTO ops.job_definition (id,source_definition_id,name,profile_key,profile_version,adapter_key,adapter_version,release_builder_key,release_builder_version,import_profile_key,import_profile_version,target_feature,dataset_id,refresh_strategy,default_run_mode,quality_policy_key,quality_policy_version,status,schedule_text,created_at,updated_at,version) VALUES ('ed406c5f-1ddf-540b-ae0b-9bd45df6f92d','dcc3a69b-47b3-599a-bda1-78d4a9538ead','ABS 2021 NSW statistical locality and LGA boundaries','abs-geography-2021','1.0.0','abs-geography-2021-source','1.0.0','reference-feature','1.0.0','abs-geography-2021','1.0.0','feature-1','abs-geography-2021','full_snapshot','full_refresh','abs-geography-2021','1.0.0','active',NULL,now(),now(),1) ON CONFLICT (id) DO NOTHING;

INSERT INTO ops.source_definition (id,name,publisher,source_url,adapter_key,cadence,licence_id,licence_url,redistribution_policy,target_features_json,status,notes,created_at,updated_at,version) VALUES ('81d57c83-5fc0-5e7e-82c5-213e5a54036b','NSW gazetted suburb boundaries','NSW Spatial Services','https://portal.spatial.nsw.gov.au/server/rest/services/NSW_Administrative_Boundaries_Theme_multiCRS/FeatureServer/2','nsw-suburb-boundaries-source','source-release-driven','cc-by','https://www.spatial.nsw.gov.au/copyright','attributed-derived-release','["feature-1"]'::jsonb,'active','Producer-owned reference source; downstream integration is separate.',now(),now(),1) ON CONFLICT (id) DO NOTHING;
INSERT INTO ops.job_definition (id,source_definition_id,name,profile_key,profile_version,adapter_key,adapter_version,release_builder_key,release_builder_version,import_profile_key,import_profile_version,target_feature,dataset_id,refresh_strategy,default_run_mode,quality_policy_key,quality_policy_version,status,schedule_text,created_at,updated_at,version) VALUES ('8bebe687-42ea-5ad8-832a-cfb161b35bff','81d57c83-5fc0-5e7e-82c5-213e5a54036b','NSW gazetted suburb boundaries','nsw-suburb-boundaries','1.0.0','nsw-suburb-boundaries-source','1.0.0','reference-feature','1.0.0','nsw-suburb-boundaries','1.0.0','feature-1','nsw-suburb-boundaries','full_snapshot','full_refresh','nsw-suburb-boundaries','1.0.0','active',NULL,now(),now(),1) ON CONFLICT (id) DO NOTHING;

INSERT INTO ops.source_definition (id,name,publisher,source_url,adapter_key,cadence,licence_id,licence_url,redistribution_policy,target_features_json,status,notes,created_at,updated_at,version) VALUES ('98c329d1-0667-5948-8472-106189cbee4f','NSW government school catchments','NSW Department of Education','https://data.nsw.gov.au/data/dataset/nsw-education-school-intake-zones-catchment-areas-for-nsw-government-schools','nsw-school-catchments-source','source-release-driven','cc-by','https://data.nsw.gov.au/data/dataset/nsw-education-school-intake-zones-catchment-areas-for-nsw-government-schools','attributed-derived-release','["feature-1"]'::jsonb,'active','Producer-owned reference source; downstream integration is separate.',now(),now(),1) ON CONFLICT (id) DO NOTHING;
INSERT INTO ops.job_definition (id,source_definition_id,name,profile_key,profile_version,adapter_key,adapter_version,release_builder_key,release_builder_version,import_profile_key,import_profile_version,target_feature,dataset_id,refresh_strategy,default_run_mode,quality_policy_key,quality_policy_version,status,schedule_text,created_at,updated_at,version) VALUES ('b59c00ac-8bb0-5434-a8b9-0b0b9d6b0ca9','98c329d1-0667-5948-8472-106189cbee4f','NSW government school catchments','nsw-school-catchments','1.0.0','nsw-school-catchments-source','1.0.0','reference-feature','1.0.0','nsw-school-catchments','1.0.0','feature-1','nsw-school-catchments','full_snapshot','full_refresh','nsw-school-catchments','1.0.0','active',NULL,now(),now(),1) ON CONFLICT (id) DO NOTHING;

INSERT INTO ops.source_definition (id,name,publisher,source_url,adapter_key,cadence,licence_id,licence_url,redistribution_policy,target_features_json,status,notes,created_at,updated_at,version) VALUES ('1d0e1ccf-9ab8-5c29-9ff9-7f245ea0286a','NSW strata scheme boundaries and register facts','NSW Spatial Services','https://portal.spatial.nsw.gov.au/server/rest/services/StrataHub/FeatureServer/0','nsw-strata-schemes-source','source-release-driven','cc-by','https://www.spatial.nsw.gov.au/copyright','attributed-derived-release','["feature-1"]'::jsonb,'active','Producer-owned reference source; downstream integration is separate.',now(),now(),1) ON CONFLICT (id) DO NOTHING;
INSERT INTO ops.job_definition (id,source_definition_id,name,profile_key,profile_version,adapter_key,adapter_version,release_builder_key,release_builder_version,import_profile_key,import_profile_version,target_feature,dataset_id,refresh_strategy,default_run_mode,quality_policy_key,quality_policy_version,status,schedule_text,created_at,updated_at,version) VALUES ('bf2c2f71-3cf4-504d-91c6-3815f0612cdb','1d0e1ccf-9ab8-5c29-9ff9-7f245ea0286a','NSW strata scheme boundaries and register facts','nsw-strata-schemes','1.0.0','nsw-strata-schemes-source','1.0.0','reference-feature','1.0.0','nsw-strata-schemes','1.0.0','feature-1','nsw-strata-schemes','full_snapshot','full_refresh','nsw-strata-schemes','1.0.0','active',NULL,now(),now(),1) ON CONFLICT (id) DO NOTHING;

INSERT INTO ops.source_definition (id,name,publisher,source_url,adapter_key,cadence,licence_id,licence_url,redistribution_policy,target_features_json,status,notes,created_at,updated_at,version) VALUES ('e4eb6cc6-62a4-5a0f-827a-770da28ede2d','NSW official amenity and facility locations','NSW Spatial Services','https://portal.spatial.nsw.gov.au/server/rest/services','nsw-amenities-source','source-release-driven','cc-by','https://www.spatial.nsw.gov.au/copyright','attributed-derived-release','["feature-1"]'::jsonb,'active','Producer-owned reference source; downstream integration is separate.',now(),now(),1) ON CONFLICT (id) DO NOTHING;
INSERT INTO ops.job_definition (id,source_definition_id,name,profile_key,profile_version,adapter_key,adapter_version,release_builder_key,release_builder_version,import_profile_key,import_profile_version,target_feature,dataset_id,refresh_strategy,default_run_mode,quality_policy_key,quality_policy_version,status,schedule_text,created_at,updated_at,version) VALUES ('1ed41e11-3da1-514f-90c8-b97f19896fcc','e4eb6cc6-62a4-5a0f-827a-770da28ede2d','NSW official amenity and facility locations','nsw-amenities','1.0.0','nsw-amenities-source','1.0.0','reference-feature','1.0.0','nsw-amenities','1.0.0','feature-1','nsw-amenities','full_snapshot','full_refresh','nsw-amenities','1.0.0','active',NULL,now(),now(),1) ON CONFLICT (id) DO NOTHING;

INSERT INTO ops.source_definition (id,name,publisher,source_url,adapter_key,cadence,licence_id,licence_url,redistribution_policy,target_features_json,status,notes,created_at,updated_at,version) VALUES ('c42f2e20-40b9-5cf1-8db8-09b93809f01f','ABS All groups CPI Sydney and Australia','Australian Bureau of Statistics','https://data.api.abs.gov.au/rest/data/ABS,CPI,2.0.0','abs-cpi-source','monthly-and-quarterly','cc-by-4-0','https://www.abs.gov.au/website-privacy-copyright-and-disclaimer','attributed-derived-release','["feature-1"]'::jsonb,'active','Producer-owned reference source; downstream integration is separate.',now(),now(),1) ON CONFLICT (id) DO NOTHING;
INSERT INTO ops.job_definition (id,source_definition_id,name,profile_key,profile_version,adapter_key,adapter_version,release_builder_key,release_builder_version,import_profile_key,import_profile_version,target_feature,dataset_id,refresh_strategy,default_run_mode,quality_policy_key,quality_policy_version,status,schedule_text,created_at,updated_at,version) VALUES ('57fbeeed-99d5-5892-9eb1-9fd6c5f0e0a5','c42f2e20-40b9-5cf1-8db8-09b93809f01f','ABS All groups CPI Sydney and Australia','abs-cpi','1.0.0','abs-cpi-source','1.0.0','reference-feature','1.0.0','abs-cpi','1.0.0','feature-1','abs-cpi','full_snapshot','full_refresh','abs-cpi','1.0.0','active',NULL,now(),now(),1) ON CONFLICT (id) DO NOTHING;
