"""Markdown review reports and append-only JSONL validation-log entries."""

from __future__ import annotations

import json
from collections.abc import Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path

from pydantic import JsonValue

from scripts.devtools.review.deterministic import MODE_TITLES
from shared_contracts.evidence_review import (
    CheckStatus,
    EvidenceReviewBundle,
    EvidenceReviewOutput,
    ReviewVerdict,
)

DECISION_START = "<!-- release-decision:start -->"
DECISION_END = "<!-- release-decision:end -->"
LOG_SCHEMA_VERSION = "1.0"


@dataclass(frozen=True, slots=True)
class ReviewRecord:
    """Everything one review produced, shared by the report and the validation log."""

    review_id: str
    mode: str
    prompt_set: str
    engine: str
    engine_label: str
    run_id: str | None
    request_id: str | None
    provider: str | None
    model: str | None
    prompts: tuple[str, ...]
    started_at: str
    finished_at: str
    duration_ms: int
    evidence_root: str
    bundle: EvidenceReviewBundle
    bundle_sha256: str
    objective_compacted: bool
    output: EvidenceReviewOutput
    model_verdict: ReviewVerdict | None
    checklist_verdict: ReviewVerdict
    verdict: ReviewVerdict
    model_output_valid: bool | None
    validation_detail: str
    fallback_reason: str | None
    phases: tuple[str, ...]
    tool_evidence: tuple[str, ...]


def render_report(record: ReviewRecord, *, log_name: str, decision_hint: str | None) -> str:
    """Render the human-readable review, newest evidence and verdict first."""
    title = MODE_TITLES[record.mode]
    run = (
        f"`{record.run_id}` (AI-mode Activity history)"
        if record.engine == "ai-mode"
        else f"`{record.run_id}` (temporary in-process run store, not in Activity history)"
        if record.run_id
        else "none"
    )
    lines = [
        f"# {title}",
        "",
        f"Generated by `uv run scripts/dev.py ai review {record.mode}`. The agentic loop "
        "reviewed the evidence below; it supports, but never replaces, human judgement.",
        "",
        "| Field | Value |",
        "|---|---|",
        f"| Verdict | **{record.verdict.value}** |",
        f"| Checklist verdict | {record.checklist_verdict.value} |",
        f"| Model verdict | {record.model_verdict.value if record.model_verdict else 'n/a'} |",
        f"| Engine | {_cell(record.engine_label)} |",
        f"| Review ID | `{record.review_id}` |",
        f"| Loop run ID | {run} |",
        f"| Request ID | {_code(record.request_id)} |",
        f"| Prompt set | `{record.prompt_set}` ({_cell(', '.join(record.prompts) or 'n/a')}) |",
        f"| Provider / model | {_cell(record.provider or 'n/a')} / "
        f"{_cell(record.model or 'n/a')} |",
        f"| Phases | {_cell(' → '.join(record.phases) or 'n/a')} |",
        f"| Started / finished | {record.started_at} / {record.finished_at} "
        f"({record.duration_ms} ms) |",
        f"| Evidence root | `{record.evidence_root}` |",
        f"| Bundle SHA-256 | `{record.bundle_sha256}` |",
        f"| Validation log | `{log_name}` |",
        "",
    ]
    if record.fallback_reason:
        lines += [
            f"> **Fallback:** the AI-mode review was not used ({_cell(record.fallback_reason)}). "
            "This report is the deterministic checklist review.",
            "",
        ]
    lines += ["## Summary", "", record.output.summary, ""]
    lines += [
        "## Inputs",
        "",
        "| Path | Status | Bytes | SHA-256 |",
        "|---|---|---:|---|",
    ]
    for item in record.bundle.inputs:
        status = item.status.value + (f" ({item.detail})" if item.detail else "")
        lines.append(
            f"| `{_cell(item.path)}` | {_cell(status)} | "
            f"{'' if item.bytes is None else item.bytes} | {_code(item.sha256)} |"
        )
    if not record.bundle.inputs:
        lines.append("| none | | | |")
    passed = sum(1 for check in record.bundle.checks if check.status is CheckStatus.PASSED)
    lines += [
        "",
        f"## Checklist ({passed}/{len(record.bundle.checks)} passed)",
        "",
        "| Check | Required | Result | Detail |",
        "|---|---|---|---|",
    ]
    for check in record.bundle.checks:
        mark = "pass" if check.status is CheckStatus.PASSED else "**FAIL**"
        lines.append(
            f"| `{check.id}` {_cell(check.title)} | {'yes' if check.required else 'advisory'} "
            f"| {mark} | {_cell(check.detail)} |"
        )
    lines += ["", "## Findings", ""]
    if record.output.findings:
        lines += ["| Severity | Area | Finding | Evidence |", "|---|---|---|---|"]
        for finding in record.output.findings:
            lines.append(
                f"| {finding.severity.value} | {_cell(finding.area)} | {_cell(finding.message)} "
                f"| {_cell(', '.join(finding.evidence_refs))} |"
            )
    else:
        lines.append("No findings.")
    lines += ["", "## Risks", ""]
    lines += _bullets(
        f"**{risk.severity.value}**: {risk.description} Mitigation: {risk.mitigation}"
        for risk in record.output.risks
    )
    lines += ["", "## Recommendations", ""]
    lines += _bullets(record.output.recommendations)
    lines += [
        "",
        "## Validation",
        "",
        f"- Output schema: `evidence-review-output.v1` — {_cell(record.validation_detail)}",
        "- The verdict is the stricter of the model verdict and the deterministic checklist "
        "verdict; a model cannot relax a failed required check.",
        f"- Tool evidence recorded by the run: {len(record.tool_evidence)} reference(s).",
        "",
        "## Collected facts",
        "",
        "```json",
        json.dumps(record.bundle.facts, indent=2, sort_keys=True),
        "```",
    ]
    if decision_hint is not None:
        lines += ["", "## Human release decision", "", DECISION_START, decision_hint, DECISION_END]
    return "\n".join(lines) + "\n"


def log_entry(
    record: ReviewRecord, *, report_path: str, report_sha256: str
) -> dict[str, JsonValue]:
    """Build one validation-log line: identities, hashes, every check and the verdicts."""
    return {
        "schema_version": LOG_SCHEMA_VERSION,
        "event": "review_completed",
        "review_id": record.review_id,
        "mode": record.mode,
        "prompt_set": record.prompt_set,
        "prompts": list(record.prompts),
        "engine": record.engine,
        "run_id": record.run_id,
        "request_id": record.request_id,
        "provider": record.provider,
        "model": record.model,
        "started_at": record.started_at,
        "finished_at": record.finished_at,
        "duration_ms": record.duration_ms,
        "evidence_root": record.evidence_root,
        "bundle_sha256": record.bundle_sha256,
        "objective_compacted": record.objective_compacted,
        "inputs": [
            {
                "path": item.path,
                "status": item.status.value,
                "sha256": item.sha256,
                "bytes": item.bytes,
            }
            for item in record.bundle.inputs
        ],
        "checks": [
            {"id": check.id, "status": check.status.value, "required": check.required}
            for check in record.bundle.checks
        ],
        "checks_passed": sum(
            1 for check in record.bundle.checks if check.status is CheckStatus.PASSED
        ),
        "checks_failed": sum(
            1 for check in record.bundle.checks if check.status is CheckStatus.FAILED
        ),
        "phases": list(record.phases),
        "tool_evidence": list(record.tool_evidence[:20]),
        "model_output_valid": record.model_output_valid,
        "validation_detail": record.validation_detail,
        "fallback_reason": record.fallback_reason,
        "findings": len(record.output.findings),
        "risks": len(record.output.risks),
        "recommendations": len(record.output.recommendations),
        "model_verdict": record.model_verdict.value if record.model_verdict else None,
        "checklist_verdict": record.checklist_verdict.value,
        "verdict": record.verdict.value,
        "report_path": report_path,
        "report_sha256": report_sha256,
    }


def append_log(path: Path, entry: Mapping[str, JsonValue]) -> None:
    """Append one compact JSON line; never rewrite earlier entries."""
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8", newline="\n") as stream:
        stream.write(json.dumps(entry, sort_keys=True, separators=(",", ":")) + "\n")


def read_log(path: Path, *, max_bytes: int = 4 * 1024 * 1024) -> list[dict[str, JsonValue]]:
    """Read the tail of a validation log, skipping a partially written final line."""
    if not path.is_file():
        return []
    size = path.stat().st_size
    with path.open("rb") as stream:
        stream.seek(max(0, size - max_bytes))
        raw = stream.read().decode("utf-8", errors="replace")
    entries: list[dict[str, JsonValue]] = []
    for line in raw.splitlines():
        try:
            value = json.loads(line)
        except json.JSONDecodeError:
            continue
        if isinstance(value, dict):
            entries.append(value)
    return entries


def replace_decision_block(report: str, block: str) -> str:
    """Swap the marked human-decision section of a cloud review report."""
    start = report.find(DECISION_START)
    end = report.find(DECISION_END)
    if start < 0 or end < start:
        return (
            report.rstrip("\n")
            + f"\n\n## Human release decision\n\n{DECISION_START}\n"
            + (f"{block}\n{DECISION_END}\n")
        )
    return report[: start + len(DECISION_START)] + "\n" + block + "\n" + report[end:]


def _bullets(items: Iterable[str]) -> list[str]:
    rendered = [f"- {_inline(item)}" for item in items]
    return rendered or ["None recorded."]


def _cell(text: str) -> str:
    return _inline(text).replace("|", "\\|")


def _inline(text: str) -> str:
    return " ".join(text.split())


def _code(value: str | None) -> str:
    return f"`{value}`" if value else "n/a"


def table(rows: Sequence[tuple[str, str]]) -> list[str]:
    """Render a two-column field/value table."""
    return ["| Field | Value |", "|---|---|", *(f"| {key} | {value} |" for key, value in rows)]
