"""Generate deterministic enabled-feature projections from validated onboarding metadata."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

import yaml

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.onboarding import (
    REPOSITORY_ROOT,
    discover_feature_manifests,
    load_enabled_projection,
)
from shared_contracts import FeatureManifest, load_feature_manifests

JSON_OUTPUT = Path("deployment/enabled-features.v1.json")
JAVASCRIPT_OUTPUT = Path("shared/frontend/generated/enabled-features.js")
NGINX_OUTPUT = Path("shared/frontend/generated/enabled-feature-routes.conf")
COMPOSE_OUTPUT = Path("deployment/enabled-features.compose.yml")
FRAGMENT_OUTPUT = Path("shared/frontend/fragments/research-areas.html")
PLANNED_FRAGMENT = Path("shared/frontend/fragments/planned-research-areas.html")


def _json_payload(root: Path) -> str:
    projection = load_enabled_projection(root)
    return json.dumps(projection.model_dump(mode="json"), indent=2, sort_keys=True) + "\n"


def _javascript_payload(root: Path) -> str:
    projection = load_enabled_projection(root)
    values = []
    for feature in projection.features:
        frontend_route = next((route for route in feature.routes if route.kind == "frontend"), None)
        backend_route = next((route for route in feature.routes if route.kind == "backend"), None)
        values.append(
            {
                "featureKey": feature.feature_key,
                "displayName": next(
                    manifest.display_name
                    for manifest in _manifests(root)
                    if manifest.feature_key == feature.feature_key
                ),
                "owner": feature.owner,
                "frontendBase": frontend_route.path if frontend_route else None,
                "backendBase": backend_route.path if backend_route else None,
                "healthPath": feature.health_path,
                "publicHealthPath": (
                    f"/api/shared-health/{frontend_route.path.rstrip('/').rsplit('/', 1)[-1]}"
                    if frontend_route
                    else None
                ),
            }
        )
    encoded = json.dumps(values, indent=2, sort_keys=True)
    return (
        "// Generated by scripts/generate_deployment.py; do not edit by hand.\n"
        f"const VALUES = {encoded};\n\n"
        "export const ENABLED_FEATURES = "
        "Object.freeze(VALUES.map((item) => Object.freeze(item)));\n"
    )


def _manifests(root: Path) -> tuple[FeatureManifest, ...]:
    return load_feature_manifests(discover_feature_manifests(root))


def _proxy_lines(upstream: str, *, timeout: str = "10s") -> list[str]:
    return [
        f"        proxy_pass {upstream};",
        "        proxy_http_version 1.1;",
        "        proxy_set_header Host $host;",
        "        proxy_set_header X-Request-ID $correlation_request_id;",
        "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
        "        proxy_set_header X-Forwarded-Proto $scheme;",
        f"        proxy_read_timeout {timeout};",
    ]


def _nginx_payload(root: Path) -> str:
    lines = ["# Generated by scripts/generate_deployment.py; do not edit by hand."]
    for index, feature in enumerate(load_enabled_projection(root).features):
        frontend = feature.frontend
        backend = next((route for route in feature.routes if route.kind == "backend"), None)
        frontend_route = next((route for route in feature.routes if route.kind == "frontend"), None)
        if frontend is None or frontend_route is None:
            continue
        frontend_base = frontend_route.path.rstrip("/")
        frontend_variable = f"$enabled_feature_{index}_frontend"
        lines.append(f"set {frontend_variable} http://{frontend.service}:{frontend.internal_port};")
        if backend is not None:
            backend_settings = next(
                manifest.onboarding.backend
                for manifest in _manifests(root)
                if manifest.feature_key == feature.feature_key and manifest.onboarding is not None
            )
            assert backend_settings is not None
            backend_variable = f"$enabled_feature_{index}_backend"
            lines.append(
                f"set {backend_variable} http://{backend.service}:{backend_settings.internal_port};"
            )
        else:
            backend_settings = None
            backend_variable = ""
        lines.extend(
            [
                f"location = {frontend_base} {{",
                f"        return 308 {frontend_base}/;",
                "}",
                f"location ^~ {frontend_base}/ {{",
                f"        rewrite ^{re.escape(frontend_base)}/(.*)$ /$1 break;",
                *_proxy_lines(frontend_variable),
                f"        proxy_set_header X-Forwarded-Prefix {frontend_base};",
                "}",
            ]
        )
        if backend is None or backend_settings is None:
            continue
        slug = frontend_base.rsplit("/", maxsplit=1)[-1]
        lines.extend(
            [
                f"location = /api/shared-health/{slug} {{",
                *_proxy_lines(f"{backend_variable}{feature.health_path}", timeout="6s"),
                "}",
            ]
        )
        for path in (backend.path, *backend_settings.additional_paths):
            normalized = path.rstrip("/")
            lines.extend(
                [
                    f"location = {normalized} {{",
                    *_proxy_lines(f"{backend_variable}$request_uri"),
                    "}",
                    f"location ^~ {normalized}/ {{",
                    *_proxy_lines(f"{backend_variable}$request_uri"),
                    "}",
                ]
            )
    return "\n".join(lines) + "\n"


def _compose_payload(root: Path) -> str:
    projection = load_enabled_projection(root)
    services: dict[str, object] = {}
    catalog_paths = [feature.ai for feature in projection.features if feature.ai is not None]
    if catalog_paths:
        services["shared-ai-mode"] = {
            "environment": {
                "AI_MODE_TOOL_CATALOG_PATHS": ",".join(item.runtime_path for item in catalog_paths)
            },
            "volumes": [f"./{item.tool_catalog}:{item.runtime_path}:ro" for item in catalog_paths],
        }
    for feature in projection.features:
        if feature.frontend is None:
            continue
        frontend = feature.frontend
        services[frontend.service] = {
            "ports": [
                "127.0.0.1:"
                f"${{{frontend.host_port_variable}:-{frontend.host_port_default}}}:"
                f"{frontend.internal_port}"
            ]
        }
    return yaml.safe_dump(
        {"services": services}, sort_keys=True, default_flow_style=False, width=1000
    )


def _fragment_payload(root: Path) -> str:
    parts: list[str] = []
    for feature in load_enabled_projection(root).features:
        if feature.frontend is None or feature.frontend.route_fragment is None:
            continue
        parts.append((root / feature.frontend.route_fragment).read_text(encoding="utf-8").strip())
    planned = (root / PLANNED_FRAGMENT).read_text(encoding="utf-8").strip()
    if planned:
        parts.append(planned)
    return "\n".join(parts) + "\n"


def generated_outputs(root: Path = REPOSITORY_ROOT) -> dict[Path, str]:
    """Return every canonical generated projection keyed by repository-relative path."""
    return {
        JSON_OUTPUT: _json_payload(root),
        JAVASCRIPT_OUTPUT: _javascript_payload(root),
        NGINX_OUTPUT: _nginx_payload(root),
        COMPOSE_OUTPUT: _compose_payload(root),
        FRAGMENT_OUTPUT: _fragment_payload(root),
    }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files have drifted")
    parser.add_argument("--root", type=Path, default=REPOSITORY_ROOT)
    return parser


def main() -> int:
    """Write projections or prove checked-in artifacts match their validated inputs."""
    arguments = _parser().parse_args()
    root = arguments.root.resolve()
    drift: list[str] = []
    for relative, content in generated_outputs(root).items():
        destination = root / relative
        if arguments.check:
            try:
                current = destination.read_text(encoding="utf-8")
            except OSError:
                current = ""
            if current != content:
                drift.append(relative.as_posix())
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8", newline="\n")
    if drift:
        print(f"Generated deployment projections are stale: {', '.join(drift)}")
        return 1
    if arguments.check:
        print("Validated generated enabled-feature projections")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
