"""Generate deterministic enabled-feature projections from validated onboarding metadata."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path, PurePosixPath

import yaml

if __package__ in {None, ""}:
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from scripts.onboarding import (
    REPOSITORY_ROOT,
    discover_feature_manifests,
    load_enabled_projection,
)
from shared_contracts import FeatureManifest, load_feature_manifests

JSON_OUTPUT = Path("deployment/enabled-features.v1.json")
JAVASCRIPT_OUTPUT = Path("shared/frontend/generated/enabled-features.js")
NGINX_OUTPUT = Path("shared/frontend/generated/enabled-feature-routes.conf")
COMPOSE_OUTPUT = Path("deployment/enabled-features.compose.yml")
SERVICES_OUTPUT = Path("deployment/enabled-services.v1.json")
FRAGMENT_OUTPUT = Path("shared/frontend/fragments/research-areas.html")
PLANNED_FRAGMENT = Path("shared/frontend/fragments/planned-research-areas.html")


def _json_payload(root: Path) -> str:
    projection = load_enabled_projection(root)
    return json.dumps(projection.model_dump(mode="json"), indent=2, sort_keys=True) + "\n"


def _javascript_payload(root: Path) -> str:
    projection = load_enabled_projection(root)
    values = []
    for feature in projection.features:
        frontend_route = next((route for route in feature.routes if route.kind == "frontend"), None)
        backend_route = next((route for route in feature.routes if route.kind == "backend"), None)
        evidence_adapter_path = None
        if feature.evidence_adapter is not None:
            if feature.frontend is None or frontend_route is None:
                raise ValueError(
                    f"enabled feature {feature.feature_key} declares a shell evidence adapter "
                    "without a frontend asset root"
                )
            try:
                relative_adapter = PurePosixPath(feature.evidence_adapter.path).relative_to(
                    PurePosixPath(feature.frontend.asset_root)
                )
            except ValueError as exc:
                raise ValueError(
                    f"enabled feature {feature.feature_key} shell evidence adapter must be served "
                    "from its frontend asset root"
                ) from exc
            evidence_adapter_path = (
                f"{frontend_route.path.rstrip('/')}/{relative_adapter.as_posix()}"
            )
        values.append(
            {
                "featureKey": feature.feature_key,
                "displayName": next(
                    manifest.display_name
                    for manifest in _manifests(root)
                    if manifest.feature_key == feature.feature_key
                ),
                "owner": feature.owner,
                "frontendBase": frontend_route.path if frontend_route else None,
                "backendBase": backend_route.path if backend_route else None,
                "evidenceAdapterPath": evidence_adapter_path,
                "healthPath": feature.health_path,
                "publicHealthPath": (
                    f"/api/shared-health/{frontend_route.path.rstrip('/').rsplit('/', 1)[-1]}"
                    if frontend_route
                    else None
                ),
            }
        )
    encoded = json.dumps(values, indent=2, sort_keys=True)
    return (
        "// Generated by scripts/generate_deployment.py; do not edit by hand.\n"
        f"const VALUES = {encoded};\n\n"
        "export const ENABLED_FEATURES = "
        "Object.freeze(VALUES.map((item) => Object.freeze(item)));\n"
    )


def _manifests(root: Path) -> tuple[FeatureManifest, ...]:
    return load_feature_manifests(discover_feature_manifests(root))


def _proxy_lines(upstream: str, *, timeout: str = "10s") -> list[str]:
    return [
        f"        proxy_pass {upstream};",
        "        proxy_http_version 1.1;",
        "        proxy_set_header Host $host;",
        "        proxy_set_header X-Request-ID $correlation_request_id;",
        "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;",
        "        proxy_set_header X-Forwarded-Proto $scheme;",
        f"        proxy_read_timeout {timeout};",
    ]


def _nginx_payload(root: Path) -> str:
    lines = ["# Generated by scripts/generate_deployment.py; do not edit by hand."]
    for index, feature in enumerate(load_enabled_projection(root).features):
        frontend = feature.frontend
        backend = next((route for route in feature.routes if route.kind == "backend"), None)
        frontend_route = next((route for route in feature.routes if route.kind == "frontend"), None)
        if frontend is None or frontend_route is None:
            continue
        frontend_base = frontend_route.path.rstrip("/")
        frontend_variable = f"$enabled_feature_{index}_frontend"
        lines.append(f"set {frontend_variable} http://{frontend.service}:{frontend.internal_port};")
        if backend is not None:
            backend_settings = next(
                manifest.onboarding.backend
                for manifest in _manifests(root)
                if manifest.feature_key == feature.feature_key and manifest.onboarding is not None
            )
            if backend_settings is None:
                raise ValueError(f"{feature.feature_key} declares no backend onboarding")
            backend_variable = f"$enabled_feature_{index}_backend"
            lines.append(
                f"set {backend_variable} http://{backend.service}:{backend_settings.internal_port};"
            )
        else:
            backend_settings = None
            backend_variable = ""
        lines.extend(
            [
                f"location = {frontend_base} {{",
                f"        return 308 {frontend_base}/;",
                "}",
                f"location ^~ {frontend_base}/ {{",
                f"        rewrite ^{re.escape(frontend_base)}/(.*)$ /$1 break;",
                *_proxy_lines(frontend_variable),
                f"        proxy_set_header X-Forwarded-Prefix {frontend_base};",
                "}",
            ]
        )
        if backend is None or backend_settings is None:
            continue
        slug = frontend_base.rsplit("/", maxsplit=1)[-1]
        lines.extend(
            [
                f"location = /api/shared-health/{slug} {{",
                *_proxy_lines(f"{backend_variable}{feature.health_path}", timeout="6s"),
                "}",
            ]
        )
        for path in (backend.path, *backend_settings.additional_paths):
            normalized = path.rstrip("/")
            lines.extend(
                [
                    f"location = {normalized} {{",
                    *_proxy_lines(f"{backend_variable}$request_uri"),
                    "}",
                    f"location ^~ {normalized}/ {{",
                    *_proxy_lines(f"{backend_variable}$request_uri"),
                    "}",
                ]
            )
    return "\n".join(lines) + "\n"


def _compose_payload(root: Path) -> str:
    projection = load_enabled_projection(root)
    services: dict[str, object] = {}
    for service in _enabled_compose_services(root):
        services[service] = {"profiles": ["release-0"]}
    for feature in projection.features:
        if feature.frontend is None:
            continue
        frontend = feature.frontend
        frontend_projection = services.setdefault(frontend.service, {})
        if not isinstance(frontend_projection, dict):
            raise TypeError(f"{frontend.service} has a non-mapping Compose projection")
        frontend_projection["ports"] = [
            "127.0.0.1:"
            f"${{{frontend.host_port_variable}:-{frontend.host_port_default}}}:"
            f"{frontend.internal_port}"
        ]
    return yaml.safe_dump(
        {"services": services}, sort_keys=True, default_flow_style=False, width=1000
    )


def _compose_service_features(root: Path) -> dict[str, str]:
    compose_path = root / "docker-compose.yml"
    if not compose_path.is_file():
        return {}
    document = yaml.safe_load(compose_path.read_text(encoding="utf-8"))
    services = document.get("services", {}) if isinstance(document, dict) else {}
    if not isinstance(services, dict):
        raise ValueError("docker-compose.yml services must be an object")
    known_features = {manifest.feature_key for manifest in _manifests(root)}
    owned: dict[str, str] = {}
    for service, settings in services.items():
        if not isinstance(service, str) or not isinstance(settings, dict):
            continue
        labels = settings.get("labels", {})
        if not isinstance(labels, dict):
            continue
        feature_key = labels.get("propertyscope.feature-key")
        if feature_key is None:
            continue
        if not isinstance(feature_key, str) or feature_key not in known_features:
            raise ValueError(f"Compose service {service} declares an unknown feature key")
        owned[service] = feature_key
    return owned


def _enabled_compose_services(root: Path) -> tuple[str, ...]:
    projection = load_enabled_projection(root)
    enabled = {feature.feature_key for feature in projection.features}
    service_features = _compose_service_features(root)
    for feature in projection.features:
        declared_services = {route.service for route in feature.routes}
        declared_services.update(database.database_service for database in feature.databases)
        for service in declared_services:
            if service_features.get(service) != feature.feature_key:
                raise ValueError(
                    f"Compose service {service} must declare feature ownership "
                    f"{feature.feature_key}"
                )
    return tuple(
        sorted(
            service for service, feature_key in service_features.items() if feature_key in enabled
        )
    )


def _services_payload(root: Path) -> str:
    enabled = _enabled_compose_services(root)
    all_feature_services = tuple(sorted(_compose_service_features(root)))
    disabled = tuple(service for service in all_feature_services if service not in enabled)
    compose_document = yaml.safe_load((root / "docker-compose.yml").read_text(encoding="utf-8"))
    compose_services = compose_document.get("services", {})
    build_services = [
        service
        for service in enabled
        if isinstance(compose_services.get(service), dict) and "build" in compose_services[service]
    ]
    return (
        json.dumps(
            {
                "build_services": build_services,
                "disabled_services": list(disabled),
                "schema_version": 1,
                "services": list(enabled),
            },
            indent=2,
            sort_keys=True,
        )
        + "\n"
    )


def _fragment_payload(root: Path) -> str:
    parts: list[str] = []
    for feature in load_enabled_projection(root).features:
        if feature.frontend is None or feature.frontend.route_fragment is None:
            continue
        parts.append((root / feature.frontend.route_fragment).read_text(encoding="utf-8").strip())
    planned = (root / PLANNED_FRAGMENT).read_text(encoding="utf-8").strip()
    if planned:
        parts.append(planned)
    return "\n".join(parts) + "\n"


def generated_outputs(root: Path = REPOSITORY_ROOT) -> dict[Path, str]:
    """Return every canonical generated projection keyed by repository-relative path."""
    return {
        JSON_OUTPUT: _json_payload(root),
        JAVASCRIPT_OUTPUT: _javascript_payload(root),
        NGINX_OUTPUT: _nginx_payload(root),
        COMPOSE_OUTPUT: _compose_payload(root),
        SERVICES_OUTPUT: _services_payload(root),
        FRAGMENT_OUTPUT: _fragment_payload(root),
    }


def _parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if generated files have drifted")
    parser.add_argument("--root", type=Path, default=REPOSITORY_ROOT)
    return parser


def main() -> int:
    """Write projections or prove checked-in artifacts match their validated inputs."""
    arguments = _parser().parse_args()
    root = arguments.root.resolve()
    drift: list[str] = []
    for relative, content in generated_outputs(root).items():
        destination = root / relative
        if arguments.check:
            try:
                current = destination.read_text(encoding="utf-8")
            except OSError:
                current = ""
            if current != content:
                drift.append(relative.as_posix())
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8", newline="\n")
    if drift:
        print(f"Generated deployment projections are stale: {', '.join(drift)}")
        return 1
    if arguments.check:
        print("Validated generated enabled-feature projections")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
